Repository woorifisa-service-dev-4th/frontend-1st-woorilunchtogether, pull requests merged in 2025-01, with the labels that each got.

#6 feat: 음식점 데이터 추가
  data/data.js
Labels: feature

#10 feat: add result html, css
  html/list.html
  html/style.css
  html/tailwind.config.js
Labels: feature

#12 feat: 클릭시 카드 뒤집기
  html/list.html
  html/style.css
Labels: feature

#7 chore: README.md
  README.md
Labels: documentation

#16 fix: List.html feat: HTML 내 JS 기능 구현
  html/list.html
  html/style.css
Labels: feature

#17 feature: index.html, list.html js 연결
  data/data.js
  html/index.html
  html/list.html
  js/getRandomTeam.js
  js/index.js
Labels: feature

#21 메뉴 새로고침 기능 추가하기
  html/css/style.css
  html/list.html
  js/database.js
  js/getRandomTeam.js
  js/index.js
  js/list.js
Labels: feature

#24 feat: style 추가
  html/css/style.css
Labels: feature

#38 feat: 공백 구분 내 엔터 구분 추가
  js/getRandomTeam.js
Labels: feature

#59 feat : 메인페이지 자리배치도 선택 기능 추가
  index.html
  js/getRandomTeam.js
  js/index.js
  js/nameList.js
Labels: feature

#57 feat: 데이터 추가
  js/database.js
Labels: feature

#85 feat: modal 창내부 menu 스타일 수정
  index.html
  list.html
Labels: fix
